# Generated by Django 4.1 on 2022-08-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=''),
        ),
    ]
