# Generated by Django 4.1 on 2022-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qrcode',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='qr_code_images'),
        ),
    ]
