# Generated by Django 4.1 on 2022-08-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default='blank', max_length=255),
        ),
    ]
